
import Image from "next/image";
import DashboardLoginForm from "./LoginForm";
import { getDictionary } from "../../dictionary";

export const metadata = {
  title: "Admin Login | Ciao Mobile",
  description: "Generated by Next.js",
};
export default async function LoginForm({ params: { lang } }) {
  const dictionary = await getDictionary(lang);
  return (
    <div className="min-h-screen flex items-center justify-center  py-12 px-4 sm:px-6 lg:px-8">
      <Image
        // src="/assets/5.avif"
        src="/assets/6.jpg"
        alt="Workflow"
        width={3000}
        height={3000}
        className="mx-auto w-screen h-screen object-cover fixed top-0 left-0 -z-[1]"
      />
      <div className="max-w-xl mx-auto w-full  space-y-8 backdrop-blur-lg  bg-white/60 rounded-lg shadow-2xl  shadow-black">
        <DashboardLoginForm lang={lang} dictionary={dictionary.loginPage} />
      </div>
    </div>
  );
}
