import "@/app/globals.css";

import { getDictionary } from "../../dictionary";
import DashboardLayout from "./components/DashboardLayout";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
export const metadata = {
  title: "Ciao Mobile",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children, modal, ...params }) {
  const { lang } = params.params;
  const dictionary = await getDictionary(lang);
  const session = await auth();
  if (!session) return redirect(`/${lang}/login`);
  // if (session?.user?.role == "admin") {
  //   return redirect(`/${lang}/admin/dashboard`);
  // }
  // console.log(dictionary);
  return (
    <html lang="en">
      <body>
        <DashboardLayout {...params} dictionary={dictionary}>
          {children}
          {modal}
        </DashboardLayout>
      </body>
    </html>
  );
}
